// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// cpp_str_split
List cpp_str_split(std::vector< std::string > strings, int n);
RcppExport SEXP Boggler_cpp_str_split(SEXP stringsSEXP, SEXP nSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< std::vector< std::string > >::type strings(stringsSEXP );
        Rcpp::traits::input_parameter< int >::type n(nSEXP );
        List __result = cpp_str_split(strings, n);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
