# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_str_split <- function(strings, n) {
    .Call('Boggler_cpp_str_split', PACKAGE = 'Boggler', strings, n)
}

